apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: catalog-worker
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      taskCount: 1
      parallelism: 1

      template:
        spec:
          containers:
            - image: gcr.io/myon-53d85/catalog-worker:latest

              resources:
                limits:
                  memory: "2Gi"
                  cpu: "1"

              env:
                # 0 = unlimited (run until queue empty)
                - name: MAX_JOBS_PER_RUN
                  value: "0"
                # 0 = no internal deadline (Cloud Run manages timeout)
                - name: MAX_SECONDS_PER_RUN
                  value: "0"

                # Apply gate - ENABLE for production
                - name: CATALOG_APPLY_ENABLED
                  value: "true"

          # 3 hour timeout (generous for large batches)
          timeoutSeconds: 10800
