apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: catalog-quality
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
          - args:
            - --apply
            - --max-exercises
            - '1000'
            - --max-jobs
            - '200'
            command:
            - python
            - -m
            - app.reviewer.scheduled_quality_scan
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: myon-53d85
            image: gcr.io/myon-53d85/catalog-worker:latest
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
          timeoutSeconds: 3600
