apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: catalog-worker
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
          - env:
            - name: MAX_JOBS_PER_RUN
              value: '0'
            - name: MAX_SECONDS_PER_RUN
              value: '0'
            - name: CATALOG_APPLY_ENABLED
              value: 'true'
            image: gcr.io/myon-53d85/catalog-worker:latest
            resources:
              limits:
                cpu: '1'
                memory: 2Gi
          timeoutSeconds: 10800
