apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: training-analyst-worker
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      taskCount: 1
      parallelism: 1

      template:
        spec:
          containers:
            - image: gcr.io/myon-53d85/training-analyst-worker:latest

              resources:
                limits:
                  memory: "2Gi"
                  cpu: "1"

              env:
                # 0 = unlimited (run until queue empty)
                - name: MAX_JOBS_PER_RUN
                  value: "0"
                # 0 = no internal deadline
                - name: MAX_SECONDS_PER_RUN
                  value: "0"

          # 1 hour timeout
          timeoutSeconds: 3600
